const Infolist = [
    {
        image: "https://c8.alamy.com/comp/T3TG8J/portrait-of-a-young-airline-pilot-wearing-a-captains-uniform-T3TG8J.jpg",
        name: "Captain A Davis",
        position: "Pilot",
        duty: "Commercial flights, Boeing 747",
        field: "Flight Operations",
        averageSalary: "$150,000",
        dutyDetails: "Responsible for safe and efficient flight operations",
        email: "a.davis@example.com",
      },
      {
        image: "https://c8.alamy.com/comp/2H9G8XY/professional-co-pilot-giving-a-look-into-camera-from-cockpit-2H9G8XY.jpg",
        name: "First Officer D Parker",
        position: "Co-Pilot",
        duty: "Assisting Captain Davis, Airbus A320",
        field: "Flight Operations",
        averageSalary: "$100,000",
        dutyDetails: "Assist the captain in ensuring a smooth flight",
        email: "d.parker@example.com",
      },
      {
        image: "https://images.squarespace-cdn.com/content/v1/5f7a90b5928e9520fb735859/1601868095542-IJER9MAJO96YPO084BGQ/IMG_0191.JPG",
        name: "Chief Engineer Max Johnson",
        position: "Chief Engineer",
        duty: "Overseeing aircraft maintenance",
        field: "Aircraft Maintenance",
        averageSalary: "$120,000",
        dutyDetails: "Oversee and manage aircraft maintenance activities",
        email: "max.johnson@example.com",
      },
      {
        image: "https://egnatia-aviation.aero/wp-content/uploads/2023/05/Featured_Strong-Pilot-Demand-Inside-the-Black-Box-of-Pilot-Shortage-Globally-1.jpg",
        name: "Captain RJ Smith",
        position: "Pilot",
        duty: "International flights, Boeing 777",
        field: "Flight Operations",
        averageSalary: "$160,000",
        dutyDetails: "Lead pilot for long-haul international flights",
        email: "rj.smith@example.com",
      },
      {
        image: "https://www.naa.edu/wp-content/uploads/2019/06/Aviation-Maintenance-Technology_AMT_Instruction.jpg",
        name: "Avionics Technician t Adams",
        position: "Avionics Technician",
        duty: "Repairing and maintaining aircraft avionics systems",
        field: "Avionics",
        averageSalary: "$80,000",
        dutyDetails: "Diagnose and repair aircraft avionics systems",
        email: "t.adams@example.com",
      },
      {
        image: "https://www.aviationtoday.com/wp-content/uploads/2017/06/digital_copilot_2016-07-26_d8h04612-copy.jpg",
        name: "First Officer J Turner",
        position: "Co-Pilot",
        duty: "Domestic flights, Boeing 737",
        field: "Flight Operations",
        averageSalary: "$90,000",
        dutyDetails: "Assist the captain in domestic flight operations",
        email: "j.turner@example.com",
      },
      {
        image: "https://www.ziprecruiter.com/svc/fotomat/public-ziprecruiter/uploads/qna_career_path/aviation-engineer-aviation-engineer.jpg=ws1280x960",
        name: "Aircraft Engineer Michael Evans",
        position: "Aircraft Engineer",
        duty: "Designing and testing aircraft components",
        field: "Aircraft Engineering",
        averageSalary: "$130,000",
        dutyDetails: "Design and test aircraft components for efficiency",
        email: "michael.evans@example.com",
      },
      {
        image: "https://hips.hearstapps.com/hmg-prod/images/bhn-templatelongformlede-1645640853.jpeg?crop=0.752xw:1.00xh;0.125xw,0&resize=768:*",
        name: "Captain O Robinson",
        position: "Pilot",
        duty: "Regional flights, Embraer E190",
        field: "Flight Operations",
        averageSalary: "$120,000",
        dutyDetails: "Lead pilot for regional flights",
        email: "o.robinson@example.com",
      },
      {
        image: "https://calaero.edu/wp-content/uploads/2022/09/what-does-take-become-aircraft-maintenance-technician.jpg",
        name: "Maintenance Technician  Miller",
        position: "Maintenance Technician",
        duty: "Routine maintenance and inspections",
        field: "Maintenance",
        averageSalary: "$70,000",
        dutyDetails: "Perform routine maintenance and inspections on aircraft",
        email: "e.miller@example.com",
      },
      {
        image: "https://qph.cf2.quoracdn.net/main-qimg-b93c7f5329012465cc39c5baec82b2b3-lq",
        name: "First Officer B Hall",
        position: "Co-Pilot",
        duty: "Short-haul flights, Airbus A319",
        field: "Flight Operations",
        averageSalary: "$85,000",
        dutyDetails: "Assist the captain in short-haul flight operations",
        email: "b.hall@example.com",
      },
    ];
  
  export default Infolist;