const genresOptions = [
    '',
    'Action',
    'Drama',
    'Comedy',
    'Thriller',
    'Adventure',
    'Sci-Fi',
    'Romance',
    'Horror',
    'Mystery',
    'Crime',
    'Fantasy',
    'Animation',
    'Family',
    'History',
    'Biography',
    'Music',
    'War',
    'Western',
    'Documentary',
    'Sport',
    'Musical',
    'Film-Noir',
    'Short',
    'News',
    'Reality-TV',
    'Talk-Show',
    'Game-Show',
  ];
  
  export default genresOptions;